export const getThemeControl = () => ({
  bgColor: "linear-gradient(to right, #a044ff, #e738b1)",
  textColor: "white",
  helpingColor : "#a044ff",
  buttonTransparent : '#fff',
  paperColor: "#ffffff",
  spanColor: "#e738b1",
  buttonStyle: {
    width: "100%",
    padding: "12px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(to right, #a044ff, #e738b1)",
    color: "#fff",
    fontWeight: "bold",
    fontSize: "16px",
    cursor: "pointer",
    marginTop: "10px"
  },
  inputStyle : {
  backgroundColor: "#fff",
  borderRadius: "25px",
  "& .MuiOutlinedInput-root": {
    borderRadius: "25px",
    "& fieldset": { borderColor: "#d0d0d0" },
    "&:hover fieldset": { borderColor: "#b0b0b0" },
    "&.Mui-focused fieldset": { borderColor: "#a044ff" },
  },
  "& .MuiInputAdornment-root svg": { color: "#9e9e9e" },
},
errorStyle : {
  color: "#ff4d4d",
  fontSize: "12px",
  marginTop: "1px",
  fontWeight: "500",
  marginBottom: '5px !important',
  lineHeight: '1.2'
},
fieldWrapper : {
  display: "flex",
  flexDirection: "column",
  marginBottom: "18px",
},
adminPanelColor :  "#a807e7ff",
userPanelBg : "#762b94ff",
sidebarInActive : "#ec7676ff",
sidebarButtonColor : {
     width: "100%",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(to right, #740a6fff, #e738b1)",
    color: "#fff",
    fontWeight: "bold",
    cursor: "pointer",
}, 
memberHeadColor : "#095f77ab",
memberCellColor : "#0488adab",
activeColor : '#50cd49ff',
inActiveColor:'#e72d2dff',
activeColorHover: '#118b0aff',
inActiveColorHover:'#830a0aff',
deleteColor:'#e72d2dff',
deleteColorHover :'#830a0aff',
cardBg : '#6dc5bbff',
copiesColor : '#1976d2',
selectedColor : "#333",
addColor : '#20c62dff',
updateColor : '#e3be09ff',
disableColor : '#999',
imageBg : "#1976d2",

})